language: python
python:
  - "3.3"

env:
  - CFLAGS="-O0"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "export PBT_PLUGINS_PATH=$PBT_PLUGINS_PATH:plugins/"

# command to run tests
script: python3 -m unittest discover -s test; for plugin in plugins/*; do python3 -m unittest discover -s $plugin; done
